apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth

helmCharts:
  - name: dex
    repo: https://charts.dexidp.io
    version: 0.19.1
    releaseName: dex
    namespace: auth
    valuesFile: values.yaml

commonLabels:
  app.kubernetes.io/part-of: kubequest
  app.kubernetes.io/managed-by: kustomize
