apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubequest-app.name" . }}
  labels:
    {{- include "kubequest-app.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config | nindent 2 }}
